/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectomarvelstratego;

/**
 *
 * @author Gabby
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    private SistemaUsuarios sistemaUsuarios;
    private Usuario usuario;
    MenuInicio ventanaPrincipal;   
    
    public Configuracion(SistemaUsuarios sistemaUsuarios, MenuInicio ventanaPrincipal) {
        initComponents();
        this.sistemaUsuarios = sistemaUsuarios;
        this.ventanaPrincipal = ventanaPrincipal;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModoTutorial = new javax.swing.JButton();
        btnModoClasico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModoTutorial.setText("TUTORIAL");
        btnModoTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoTutorialActionPerformed(evt);
            }
        });

        btnModoClasico.setText("CLÁSICO");
        btnModoClasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoClasicoActionPerformed(evt);
            }
        });

        jLabel1.setText("CONFIGURACIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnModoTutorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnModoClasico)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModoTutorial)
                    .addComponent(btnModoClasico))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModoTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoTutorialActionPerformed
        // TODO add your handling code here:
        usuario.tutorialActivo = true;
        actualizarUsuario();
        ventanaPrincipal.setSistemaUsuarios(sistemaUsuarios);
        
        Tutorial tutorial = new Tutorial();
        tutorial.setVisible(true);
        this.dispose(); // Cerrar la ventana de configuración
    }//GEN-LAST:event_btnModoTutorialActionPerformed

    private void btnModoClasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoClasicoActionPerformed
        // TODO add your handling code here:
        usuario.tutorialActivo = false;
        actualizarUsuario();
        ventanaPrincipal.setSistemaUsuarios(sistemaUsuarios);
        this.dispose();
    }//GEN-LAST:event_btnModoClasicoActionPerformed

    private void actualizarUsuario() {
        sistemaUsuarios.actualizarUsuario(usuario);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModoClasico;
    private javax.swing.JButton btnModoTutorial;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}