/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectomarvelstratego;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabby
 */

import javax.swing.*;
import java.awt.Font;
public class PartidaNueva extends javax.swing.JFrame {

    /**
     * Creates new form PartidaNueva
     */

    SistemaUsuarios sistemaUsuarios;
    Usuario player, contrincante; 
    JComboBox bandos;
    String bandoSeleccionado;
    boolean bandoHeroes;
    
    public PartidaNueva(SistemaUsuarios sistemaUsuarios) {
        initComponents();        
        this.sistemaUsuarios = sistemaUsuarios;
        this.player = sistemaUsuarios.getUsuarioActual();
    }
    
    public void cargarUsuarios() {
        System.out.println("Cargando usuarios...");
        Usuario[] usuarios = sistemaUsuarios.getUsuariosActivos();
        System.out.println(usuarios.length);

        // Agregar los nombres a un combobox
        for (Usuario usuario : usuarios) {
            // Si es el nombre del usuario actual skipear.
            if (sistemaUsuarios.usuarioIniciado.getUsuario().equals(usuario.getUsuario())) continue;
            combobox.addItem(usuario.getUsuario());
        }
    }
    
    public void cargarBandos() {
        combobox.removeAllItems();
        
        System.out.println("Cargando bandos...");

        JLabel text = new JLabel("Escoge tu bando:");
        text.setFont(new Font("Arial", Font.BOLD, 16));
        
        bandos = new JComboBox();
        bandos.addItem("Heroes");
        bandos.addItem("Villanos");
        
        JPanel panel = new JPanel();
        
        panel.add(text);
        panel.add(bandos);
        JOptionPane.showMessageDialog(null, panel);
        
        bandoSeleccionado = (String) bandos.getSelectedItem();
        System.out.println(bandoSeleccionado);
        crearJuego();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ESCOGE TU CONTRINCANTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobox)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (contrincante == null) {            
            String nombreUsuario = (String) combobox.getSelectedItem();
            contrincante = sistemaUsuarios.getUsuario(nombreUsuario);
            dispose();
            cargarBandos();
           
        } else {
            
        }
        
        dispose();
    }
    
    public void crearJuego() {
        Usuario playerHeroes, playerVillanos;
        if (bandoSeleccionado.equals("Heroes")) {
            playerHeroes = player;
            playerVillanos = contrincante;
        }
        else {
            playerHeroes = contrincante;
            playerVillanos = player;
        }
        
        JOptionPane.showMessageDialog(null, playerHeroes.getUsuario() + " empieza con el primer turno.");
        new Juego(sistemaUsuarios, playerHeroes, playerVillanos);

        
        
            
           
    }
        
    //GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
