/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectomarvelstratego;

/**
 *
 * @author Jorge Hernandez
 */
import java.awt.Color;
public class VentanaCombate extends javax.swing.JPanel {

    /**
     * Creates new form VentanaCombat
     */
    public VentanaCombate(Personaje atacante, Personaje defensor, int ganaAtacante) {
        initComponents();
        empateLabel.setVisible(false);
        
        // Poner imagenes
        atacanteIcon.setIcon(atacante.icono);
        defensorIcon.setIcon(defensor.icono);
               
        // en el caso de que sea un empate
        if (ganaAtacante == -1) {
            atacanteLabel.setVisible(false);
            defensorLabel.setVisible(false);
            empateLabel.setVisible(true);
        } else if (ganaAtacante == 1) {
            atacanteLabel.setForeground(Color.green);
            defensorLabel.setForeground(Color.red);  
        } else {
            atacanteLabel.setText("PERDEDOR");
            defensorLabel.setText("GANADOR");
            
            atacanteLabel.setForeground(Color.red);
            defensorLabel.setForeground(Color.green);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defensorLabel = new javax.swing.JLabel();
        atacanteLabel = new javax.swing.JLabel();
        atacanteIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        defensorIcon = new javax.swing.JLabel();
        empateLabel = new javax.swing.JLabel();

        defensorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        defensorLabel.setText("PERDEDOR");

        atacanteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atacanteLabel.setText("GANADOR");

        atacanteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BlackWidowB.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("VS.");

        defensorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BlackWidowB.png"))); // NOI18N

        empateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empateLabel.setText("EMPATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(atacanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(defensorLabel)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atacanteIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(defensorIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(atacanteIcon)
                        .addComponent(defensorIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defensorLabel)
                    .addComponent(atacanteLabel))
                .addGap(18, 18, 18)
                .addComponent(empateLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atacanteIcon;
    private javax.swing.JLabel atacanteLabel;
    private javax.swing.JLabel defensorIcon;
    private javax.swing.JLabel defensorLabel;
    private javax.swing.JLabel empateLabel;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
